# Generated by Django 4.2 on 2023-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cartProductId", models.AutoField(primary_key=True, serialize=False)),
                ("productId", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("buyerUsername", models.CharField(max_length=100)),
                ("sellerUsername", models.CharField(max_length=100)),
            ],
        ),
    ]
