# Generated by Django 3.2.18 on 2023-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('status_order', models.CharField(max_length=100)),
            ],
        ),
    ]
