# Generated by Django 4.1.7 on 2023-05-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_itemorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorders',
            name='product_name',
            field=models.CharField(default='product x', max_length=100),
            preserve_default=False,
        ),
    ]
